/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as PricingImport } from './routes/pricing'
import { Route as LogoutImport } from './routes/logout'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as CandidateIndexImport } from './routes/candidate/_index'
import { Route as EmployerIndexImport } from './routes/employer/index'
import { Route as EmployerSettingsImport } from './routes/employer/settings'
import { Route as EmployerPostJobImport } from './routes/employer/postJob'
import { Route as CandidateViewJobsImport } from './routes/candidate/viewJobs'
import { Route as CandidateSettingsImport } from './routes/candidate/settings'
import { Route as CandidateDashboardImport } from './routes/candidate/dashboard'
import { Route as CandidateApplicationImport } from './routes/candidate/application'

// Create Virtual Routes

const CandidateImport = createFileRoute('/candidate')()
const ContactLazyImport = createFileRoute('/contact')()
const BlogLazyImport = createFileRoute('/blog')()
const ApplyLazyImport = createFileRoute('/apply')()
const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const CandidateRoute = CandidateImport.update({
  id: '/candidate',
  path: '/candidate',
  getParentRoute: () => rootRoute,
} as any)

const ContactLazyRoute = ContactLazyImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/contact.lazy').then((d) => d.Route))

const BlogLazyRoute = BlogLazyImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/blog.lazy').then((d) => d.Route))

const ApplyLazyRoute = ApplyLazyImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/apply.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const PricingRoute = PricingImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRoute,
} as any)

const LogoutRoute = LogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CandidateIndexRoute = CandidateIndexImport.update({
  id: '/_index',
  getParentRoute: () => CandidateRoute,
} as any)

const EmployerIndexRoute = EmployerIndexImport.update({
  id: '/employer/',
  path: '/employer/',
  getParentRoute: () => rootRoute,
} as any)

const EmployerSettingsRoute = EmployerSettingsImport.update({
  id: '/employer/settings',
  path: '/employer/settings',
  getParentRoute: () => rootRoute,
} as any)

const EmployerPostJobRoute = EmployerPostJobImport.update({
  id: '/employer/postJob',
  path: '/employer/postJob',
  getParentRoute: () => rootRoute,
} as any)

const CandidateViewJobsRoute = CandidateViewJobsImport.update({
  id: '/viewJobs',
  path: '/viewJobs',
  getParentRoute: () => CandidateRoute,
} as any)

const CandidateSettingsRoute = CandidateSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CandidateRoute,
} as any)

const CandidateDashboardRoute = CandidateDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CandidateRoute,
} as any)

const CandidateApplicationRoute = CandidateApplicationImport.update({
  id: '/application',
  path: '/application',
  getParentRoute: () => CandidateRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyLazyImport
      parentRoute: typeof rootRoute
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogLazyImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactLazyImport
      parentRoute: typeof rootRoute
    }
    '/candidate': {
      id: '/candidate'
      path: '/candidate'
      fullPath: '/candidate'
      preLoaderRoute: typeof CandidateImport
      parentRoute: typeof rootRoute
    }
    '/candidate/_index': {
      id: '/candidate/_index'
      path: '/candidate'
      fullPath: '/candidate'
      preLoaderRoute: typeof CandidateIndexImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/application': {
      id: '/candidate/application'
      path: '/application'
      fullPath: '/candidate/application'
      preLoaderRoute: typeof CandidateApplicationImport
      parentRoute: typeof CandidateImport
    }
    '/candidate/dashboard': {
      id: '/candidate/dashboard'
      path: '/dashboard'
      fullPath: '/candidate/dashboard'
      preLoaderRoute: typeof CandidateDashboardImport
      parentRoute: typeof CandidateImport
    }
    '/candidate/settings': {
      id: '/candidate/settings'
      path: '/settings'
      fullPath: '/candidate/settings'
      preLoaderRoute: typeof CandidateSettingsImport
      parentRoute: typeof CandidateImport
    }
    '/candidate/viewJobs': {
      id: '/candidate/viewJobs'
      path: '/viewJobs'
      fullPath: '/candidate/viewJobs'
      preLoaderRoute: typeof CandidateViewJobsImport
      parentRoute: typeof CandidateImport
    }
    '/employer/postJob': {
      id: '/employer/postJob'
      path: '/employer/postJob'
      fullPath: '/employer/postJob'
      preLoaderRoute: typeof EmployerPostJobImport
      parentRoute: typeof rootRoute
    }
    '/employer/settings': {
      id: '/employer/settings'
      path: '/employer/settings'
      fullPath: '/employer/settings'
      preLoaderRoute: typeof EmployerSettingsImport
      parentRoute: typeof rootRoute
    }
    '/employer/': {
      id: '/employer/'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof EmployerIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface CandidateRouteChildren {
  CandidateIndexRoute: typeof CandidateIndexRoute
  CandidateApplicationRoute: typeof CandidateApplicationRoute
  CandidateDashboardRoute: typeof CandidateDashboardRoute
  CandidateSettingsRoute: typeof CandidateSettingsRoute
  CandidateViewJobsRoute: typeof CandidateViewJobsRoute
}

const CandidateRouteChildren: CandidateRouteChildren = {
  CandidateIndexRoute: CandidateIndexRoute,
  CandidateApplicationRoute: CandidateApplicationRoute,
  CandidateDashboardRoute: CandidateDashboardRoute,
  CandidateSettingsRoute: CandidateSettingsRoute,
  CandidateViewJobsRoute: CandidateViewJobsRoute,
}

const CandidateRouteWithChildren = CandidateRoute._addFileChildren(
  CandidateRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/about': typeof AboutLazyRoute
  '/apply': typeof ApplyLazyRoute
  '/blog': typeof BlogLazyRoute
  '/contact': typeof ContactLazyRoute
  '/candidate': typeof CandidateIndexRoute
  '/candidate/application': typeof CandidateApplicationRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/settings': typeof CandidateSettingsRoute
  '/candidate/viewJobs': typeof CandidateViewJobsRoute
  '/employer/postJob': typeof EmployerPostJobRoute
  '/employer/settings': typeof EmployerSettingsRoute
  '/employer': typeof EmployerIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/about': typeof AboutLazyRoute
  '/apply': typeof ApplyLazyRoute
  '/blog': typeof BlogLazyRoute
  '/contact': typeof ContactLazyRoute
  '/candidate': typeof CandidateIndexRoute
  '/candidate/application': typeof CandidateApplicationRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/settings': typeof CandidateSettingsRoute
  '/candidate/viewJobs': typeof CandidateViewJobsRoute
  '/employer/postJob': typeof EmployerPostJobRoute
  '/employer/settings': typeof EmployerSettingsRoute
  '/employer': typeof EmployerIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/about': typeof AboutLazyRoute
  '/apply': typeof ApplyLazyRoute
  '/blog': typeof BlogLazyRoute
  '/contact': typeof ContactLazyRoute
  '/candidate': typeof CandidateRouteWithChildren
  '/candidate/_index': typeof CandidateIndexRoute
  '/candidate/application': typeof CandidateApplicationRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/settings': typeof CandidateSettingsRoute
  '/candidate/viewJobs': typeof CandidateViewJobsRoute
  '/employer/postJob': typeof EmployerPostJobRoute
  '/employer/settings': typeof EmployerSettingsRoute
  '/employer/': typeof EmployerIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/pricing'
    | '/register'
    | '/about'
    | '/apply'
    | '/blog'
    | '/contact'
    | '/candidate'
    | '/candidate/application'
    | '/candidate/dashboard'
    | '/candidate/settings'
    | '/candidate/viewJobs'
    | '/employer/postJob'
    | '/employer/settings'
    | '/employer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/pricing'
    | '/register'
    | '/about'
    | '/apply'
    | '/blog'
    | '/contact'
    | '/candidate'
    | '/candidate/application'
    | '/candidate/dashboard'
    | '/candidate/settings'
    | '/candidate/viewJobs'
    | '/employer/postJob'
    | '/employer/settings'
    | '/employer'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/logout'
    | '/pricing'
    | '/register'
    | '/about'
    | '/apply'
    | '/blog'
    | '/contact'
    | '/candidate'
    | '/candidate/_index'
    | '/candidate/application'
    | '/candidate/dashboard'
    | '/candidate/settings'
    | '/candidate/viewJobs'
    | '/employer/postJob'
    | '/employer/settings'
    | '/employer/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  AboutLazyRoute: typeof AboutLazyRoute
  ApplyLazyRoute: typeof ApplyLazyRoute
  BlogLazyRoute: typeof BlogLazyRoute
  ContactLazyRoute: typeof ContactLazyRoute
  CandidateRoute: typeof CandidateRouteWithChildren
  EmployerPostJobRoute: typeof EmployerPostJobRoute
  EmployerSettingsRoute: typeof EmployerSettingsRoute
  EmployerIndexRoute: typeof EmployerIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  AboutLazyRoute: AboutLazyRoute,
  ApplyLazyRoute: ApplyLazyRoute,
  BlogLazyRoute: BlogLazyRoute,
  ContactLazyRoute: ContactLazyRoute,
  CandidateRoute: CandidateRouteWithChildren,
  EmployerPostJobRoute: EmployerPostJobRoute,
  EmployerSettingsRoute: EmployerSettingsRoute,
  EmployerIndexRoute: EmployerIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/logout",
        "/pricing",
        "/register",
        "/about",
        "/apply",
        "/blog",
        "/contact",
        "/candidate",
        "/employer/postJob",
        "/employer/settings",
        "/employer/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/pricing": {
      "filePath": "pricing.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/apply": {
      "filePath": "apply.lazy.tsx"
    },
    "/blog": {
      "filePath": "blog.lazy.tsx"
    },
    "/contact": {
      "filePath": "contact.lazy.tsx"
    },
    "/candidate": {
      "filePath": "candidate",
      "children": [
        "/candidate/_index",
        "/candidate/application",
        "/candidate/dashboard",
        "/candidate/settings",
        "/candidate/viewJobs"
      ]
    },
    "/candidate/_index": {
      "filePath": "candidate/_index.tsx",
      "parent": "/candidate"
    },
    "/candidate/application": {
      "filePath": "candidate/application.tsx",
      "parent": "/candidate"
    },
    "/candidate/dashboard": {
      "filePath": "candidate/dashboard.tsx",
      "parent": "/candidate"
    },
    "/candidate/settings": {
      "filePath": "candidate/settings.tsx",
      "parent": "/candidate"
    },
    "/candidate/viewJobs": {
      "filePath": "candidate/viewJobs.tsx",
      "parent": "/candidate"
    },
    "/employer/postJob": {
      "filePath": "employer/postJob.tsx"
    },
    "/employer/settings": {
      "filePath": "employer/settings.tsx"
    },
    "/employer/": {
      "filePath": "employer/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
