/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as PricingImport } from './routes/pricing'
import { Route as LogoutImport } from './routes/logout'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as EmployerIndexImport } from './routes/employer/index'
import { Route as CandidateIndexImport } from './routes/candidate/index'
import { Route as EmployerSettingsImport } from './routes/employer/settings'
import { Route as EmployerPostJobImport } from './routes/employer/postJob'

// Create Virtual Routes

const ContactLazyImport = createFileRoute('/contact')()
const BlogLazyImport = createFileRoute('/blog')()
const ApplyLazyImport = createFileRoute('/apply')()
const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const ContactLazyRoute = ContactLazyImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/contact.lazy').then((d) => d.Route))

const BlogLazyRoute = BlogLazyImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/blog.lazy').then((d) => d.Route))

const ApplyLazyRoute = ApplyLazyImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/apply.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const PricingRoute = PricingImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRoute,
} as any)

const LogoutRoute = LogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EmployerIndexRoute = EmployerIndexImport.update({
  id: '/employer/',
  path: '/employer/',
  getParentRoute: () => rootRoute,
} as any)

const CandidateIndexRoute = CandidateIndexImport.update({
  id: '/candidate/',
  path: '/candidate/',
  getParentRoute: () => rootRoute,
} as any)

const EmployerSettingsRoute = EmployerSettingsImport.update({
  id: '/employer/settings',
  path: '/employer/settings',
  getParentRoute: () => rootRoute,
} as any)

const EmployerPostJobRoute = EmployerPostJobImport.update({
  id: '/employer/postJob',
  path: '/employer/postJob',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyLazyImport
      parentRoute: typeof rootRoute
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogLazyImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactLazyImport
      parentRoute: typeof rootRoute
    }
    '/employer/postJob': {
      id: '/employer/postJob'
      path: '/employer/postJob'
      fullPath: '/employer/postJob'
      preLoaderRoute: typeof EmployerPostJobImport
      parentRoute: typeof rootRoute
    }
    '/employer/settings': {
      id: '/employer/settings'
      path: '/employer/settings'
      fullPath: '/employer/settings'
      preLoaderRoute: typeof EmployerSettingsImport
      parentRoute: typeof rootRoute
    }
    '/candidate/': {
      id: '/candidate/'
      path: '/candidate'
      fullPath: '/candidate'
      preLoaderRoute: typeof CandidateIndexImport
      parentRoute: typeof rootRoute
    }
    '/employer/': {
      id: '/employer/'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof EmployerIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/about': typeof AboutLazyRoute
  '/apply': typeof ApplyLazyRoute
  '/blog': typeof BlogLazyRoute
  '/contact': typeof ContactLazyRoute
  '/employer/postJob': typeof EmployerPostJobRoute
  '/employer/settings': typeof EmployerSettingsRoute
  '/candidate': typeof CandidateIndexRoute
  '/employer': typeof EmployerIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/about': typeof AboutLazyRoute
  '/apply': typeof ApplyLazyRoute
  '/blog': typeof BlogLazyRoute
  '/contact': typeof ContactLazyRoute
  '/employer/postJob': typeof EmployerPostJobRoute
  '/employer/settings': typeof EmployerSettingsRoute
  '/candidate': typeof CandidateIndexRoute
  '/employer': typeof EmployerIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/about': typeof AboutLazyRoute
  '/apply': typeof ApplyLazyRoute
  '/blog': typeof BlogLazyRoute
  '/contact': typeof ContactLazyRoute
  '/employer/postJob': typeof EmployerPostJobRoute
  '/employer/settings': typeof EmployerSettingsRoute
  '/candidate/': typeof CandidateIndexRoute
  '/employer/': typeof EmployerIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/pricing'
    | '/register'
    | '/about'
    | '/apply'
    | '/blog'
    | '/contact'
    | '/employer/postJob'
    | '/employer/settings'
    | '/candidate'
    | '/employer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/pricing'
    | '/register'
    | '/about'
    | '/apply'
    | '/blog'
    | '/contact'
    | '/employer/postJob'
    | '/employer/settings'
    | '/candidate'
    | '/employer'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/logout'
    | '/pricing'
    | '/register'
    | '/about'
    | '/apply'
    | '/blog'
    | '/contact'
    | '/employer/postJob'
    | '/employer/settings'
    | '/candidate/'
    | '/employer/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  AboutLazyRoute: typeof AboutLazyRoute
  ApplyLazyRoute: typeof ApplyLazyRoute
  BlogLazyRoute: typeof BlogLazyRoute
  ContactLazyRoute: typeof ContactLazyRoute
  EmployerPostJobRoute: typeof EmployerPostJobRoute
  EmployerSettingsRoute: typeof EmployerSettingsRoute
  CandidateIndexRoute: typeof CandidateIndexRoute
  EmployerIndexRoute: typeof EmployerIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  AboutLazyRoute: AboutLazyRoute,
  ApplyLazyRoute: ApplyLazyRoute,
  BlogLazyRoute: BlogLazyRoute,
  ContactLazyRoute: ContactLazyRoute,
  EmployerPostJobRoute: EmployerPostJobRoute,
  EmployerSettingsRoute: EmployerSettingsRoute,
  CandidateIndexRoute: CandidateIndexRoute,
  EmployerIndexRoute: EmployerIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/logout",
        "/pricing",
        "/register",
        "/about",
        "/apply",
        "/blog",
        "/contact",
        "/employer/postJob",
        "/employer/settings",
        "/candidate/",
        "/employer/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/pricing": {
      "filePath": "pricing.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/apply": {
      "filePath": "apply.lazy.tsx"
    },
    "/blog": {
      "filePath": "blog.lazy.tsx"
    },
    "/contact": {
      "filePath": "contact.lazy.tsx"
    },
    "/employer/postJob": {
      "filePath": "employer/postJob.tsx"
    },
    "/employer/settings": {
      "filePath": "employer/settings.tsx"
    },
    "/candidate/": {
      "filePath": "candidate/index.tsx"
    },
    "/employer/": {
      "filePath": "employer/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
